describe('Verify Case Studies', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.contains('Case Studies')
    .should('be.visible')
    .click()
});

  it('should verify HoneyBricks case studies', () => {
    cy.contains('HoneyBricks expands investment accessibility')
    .should('have.attr','href','/case-studies/honeybricks')
    .click()

    cy.title()
    .should("include","HoneyBricks expands investment accessibility")
    cy.get('.project-page-banner-description')
    .should('have.text','HoneyBricks used blockchain for secure real estate investment, supporting 3,500 investors and managing over $5 million.')
    cy.get('.case-study-rich-text > h2 > strong')
    .should('have.text','Making the exclusive world of private real estate inclusive')
    cy.get('.case-study-rich-text > :nth-child(2)')
    .should('have.text','HoneyBricks is on a mission to unlock the potential of real estate. Their technology platform connects investors with high-quality multifamily investment opportunities in the United States.')
    cy.get('.case-study-rich-text > :nth-child(3)')
    .should('have.text','Devsinc worked with the internal development team to build out a modern software-as-a-service application platform that used blockchain technology to power its infrastructure.')

    cy.get('.project-solutions-rich-text > h2 > strong')
    .should('have.text','Deep Financial Integrations')
    cy.get('.project-solutions-rich-text > ul > :nth-child(1)')
    .should('have.text','Secure Connections: HoneyBricks needed to establish several secure connections with different payment gateway services to ensure smooth transaction processing, which involved implementing comprehensive error handling and fallback mechanisms for reliability.')
    cy.get('.project-solutions-rich-text > ul > :nth-child(2)')
    .should('have.text','Encompassing Compliance Regulations: HoneyBricks needed to navigate a complex landscape of financial regulations, such as PCI DSS, GDPR, KYC, and AML, to maintain compliance. It required continuous monitoring and updating of systems to meet changing regulations, along with implementing robust data protection measures to secure financial information.')
    cy.get('.project-solutions-rich-text > ul > :nth-child(3)')
    .should('have.text','Feature Flagging for Deployment: Updating the live web application without disrupting user activities demanded strategies like feature flags for dynamic feature management. The process involved staging environments for testing and employing deployment techniques like blue-green deployments or canary releases to ensure seamless user experiences.')
    cy.get('.project-solutions-rich-text > ul > :nth-child(4)')
    .should('have.text','Quality Assurance: Ensuring the reliability of new features and functional changes required a strong focus on QA, with both automated and manual testing strategies. This was supported by CI/CD pipelines to facilitate streamlined testing and deployment, minimizing the risk of bugs or regressions impacting users.')

    cy.get(':nth-child(5) > .w-layout-blockcontainer > .project-result-grid-block > .result-rich-text > h2 > strong')
    .should('have.text','How Devsinc supports HoneyBricks?')
    cy.get(':nth-child(5) > .w-layout-blockcontainer > .project-result-grid-block > .result-rich-text > p')
    .should('have.text','Besides facing the technical challenges, we were able to resolve the complexities of requirements with ease and flexibility, as follows:')
    cy.get('.result-rich-text > ul > :nth-child(1)')
    .should('have.text','Full-Stack Development: The platform was tailored to ensure flexible and scalable operations across all transactional processes. This development involved a selection of a technology stack designed for scalability and security, employing a microservices architecture to enhance modularity and facilitate future expansion, and implementing stringent security measures to protect user data and maintain privacy.')
    cy.get('.result-rich-text > ul > :nth-child(2)')
    .should('have.text','Customizable Modules: To enable the platform to support payment methods, customizable and modular code sets were employed for various payment gateway integrations. This approach required the development of robust APIs and the use of SDKs provided by these gateways, coupled with custom-built logic for managing the nuances of payment processing, ensuring seamless error handling, and maintaining consistent data across transactions.')
    cy.get('.result-rich-text > ul > :nth-child(3)')
    .should('have.text','Blockchain Technology: Blockchain technology, through the use of smart contracts, was harnessed to automate critical transactional operations, thereby bolstering the platform\'s security and transparency.')
    cy.get('.result-rich-text > ul > :nth-child(4)')
    .should('have.text','KYC Standards Compliance: The system was developed to facilitate cryptocurrency transactions and ensure these transactions comply with KYC standards. This involved integrating real-time mechanisms for crypto-to-fiat conversions, secure management of digital wallets, and comprehensive blockchain integrations to support a variety of cryptocurrencies.')

    cy.get(':nth-child(6) > .w-layout-blockcontainer > .project-result-grid-block > .result-rich-text > h2 > strong')
    .should('have.text','Results that HoneyBricks achieved')
    cy.get(':nth-child(6) > .w-layout-blockcontainer > .project-result-grid-block > .result-rich-text > p')
    .should('have.text','The outturns were plentiful. According to NewsWire Reports, HoneyBricks enjoyed multiple benefits:')
    cy.get('ol > :nth-child(1)')
    .should('have.text','Onboarded 3,500+ investors: Grew their platform to support 3,500 investors, showing strong growth.')
    cy.get('ol > :nth-child(2)')
    .should('have.text','7 payment gateway integrations: Devsinc built and supported 7 different payment gateways to give investors multiple investment options.')
    cy.get('ol > :nth-child(3)')
    .should('have.text','$5 million+ of investment managed: Handled more than $5 million in different currencies, proving our financial management skills.')
    cy.get('ol > :nth-child(4)')
    .should('have.text','Acquired by EquityMultiple: Their success led to being bought by EquityMultiple, marking a big achievement for us.')

    cy.get('.project-button-link.left').click()
    cy.get('.h1-details-page')
    .should('have.text','Intellirent’s Approach to Smarter Leasing')

    cy.get('.project-next-button-link-icon').click()
    cy.get('.h1-details-page')
    .should('have.text','HoneyBricks expands investment accessibility')
  })

  it('should verify Recurate case studies', () => {
    cy.contains('How did Recurate Unlocked ReCommerce')
    .should('have.attr','href','/case-studies/recurate')
    .click()

    cy.title()
    .should("include","How did Recurate Unlocked ReCommerce")
    cy.get('.project-page-banner-description')
    .should('have.text','Provides the perfect solution for the resale marketplace covering the E-Commerce P2P model')
    cy.get('.case-study-rich-text > h2 > strong')
    .should('have.text','Tracing Recurate’s Path to Unlocking ReCommerce Industry')
    cy.get('.case-study-rich-text > :nth-child(2)')
    .should('have.text','Recurate is a full-service e-commerce partner that enables a product’s peer-to-peer marketing directly on e-commerce stores.')
    cy.get('.case-study-rich-text > :nth-child(3)')
    .should('have.text','It has emerged as a pioneering player in the fashion industry, offering a solution to the problem. They designed a resale operating system that empowers brands to own their second-hand market through a custom resale marketplace. Recurate’s approach involves integrating various resale models, including peer-to-peer reselling, trade-ins, and much more innovation into a brand’s omnichannel strategy.')

    cy.get('.project-solutions-rich-text > h2 > strong')
    .should('have.text','Complexities in Achieving Fashion’s Resale Goals')
    cy.get('.project-solutions-rich-text > :nth-child(2)')
    .should('have.text','Some of the major challenges were as follows while working on this project:')
    cy.get('.project-solutions-rich-text > :nth-child(3)')
    .should('have.text','It was hard developing and maintaining the same markup for multiple platforms like Shopify, Magento, Bigcommerce, and Salesforce. Every platform has its own specifications of eCommerce and its particular attributes. It was so difficult to replicate the business logic many times. Data security and performance were also the toughest challenges as it was suspected that on the admin portal, anyone would be able to see each other\'s data accidentally or intentionally, and generating queries was a total hassle. Image uploading was crucial in this idea as we were using jQuery-uploader initially, custom styling was another challenge, also, this plugin was not supportive with all of the browsers on all devices.')

    cy.get('.result-rich-text > h2 > strong')
    .should('have.text','How We Stepped in While Handling Our Clients’ Pain Points?')
    cy.get('.result-rich-text > :nth-child(2)')
    .should('have.text','Besides facing the technical challenges, we were able to resolve the complexities of requirements with ease and flexibility, as follows:')
    cy.get('ul > :nth-child(1)')
    .should('have.text','We created a Headless Frontend API through which HTML markup was returned in response and using the styles and scripts from CDNs, the markup renderer (in the platform’s connector app) showcased the unified Frontend interface.')
    cy.get('ul > :nth-child(2)')
    .should('have.text','We developed the wrappers for every single platform. It is imperative to know that each wrapper defines the rules, webhooks, and field mapping, and offers a few customizations to the platform, following the generic API to execute different business operations.')
    cy.get('ul > :nth-child(3)')
    .should('have.text','We resolved data security and performance issues by data sharding using tenants of PostgreSQL databases which created clusters for each store and hence made searches and queries flexible to manage from the limited set of data instead of the whole database.')
    cy.get('ul > :nth-child(4)')
    .should('have.text','We built the customized solution to upload images, using HTML, and vanilla JavaScript to avoid conflicts with the store theme along with the support of Node.js and AWS lambda. Also, we used Sharp and Jimp to process the images and store them in the bucket in the form of streams')

    cy.get('.heading-8')
    .should('have.text','Multifaceted Benefits Maximized Through Our Services')
    cy.get('#w-node-f63917fc-0bab-68ec-ed14-5c4d83105098-10a26edf > .charcol-grey-20')
    .should('have.text','Assured Sustainability')
    cy.get('#w-node-f63917fc-0bab-68ec-ed14-5c4d83105098-10a26edf > p')
    .should('have.text','By enabling customers to resell preloved items, brands have significantly reduced the number of discarded products, contributing to a more sustainable fashion industry.')
    cy.get('#w-node-b2706c5f-a224-fd15-7b6d-ba1158045284-10a26edf > .charcol-grey-20')
    .should('have.text','Customer Engagement')
    cy.get('#w-node-b2706c5f-a224-fd15-7b6d-ba1158045284-10a26edf > p')
    .should('have.text','Brands have engaged customers throughout the entire product lifecycle, fostering brand loyalty and a sense of community among their customer base.')
    cy.get('#w-node-_6a23ea53-4b33-c074-a631-fffba163e780-10a26edf > .charcol-grey-20')
    .should('have.text','Dedicated Donations')
    cy.get('#w-node-_6a23ea53-4b33-c074-a631-fffba163e780-10a26edf > p')
    .should('have.text','Many renowned brands demonstrated their dedication to sustainability not only through their product materials but also through initiatives like tree planting and donations to environmental causes.')
    cy.get('#w-node-_94a3001f-91a9-a4f4-9fb9-b38b9fe8238d-10a26edf > .charcol-grey-20')
    .should('have.text','Valuable Opportunities')
    cy.get('#w-node-_94a3001f-91a9-a4f4-9fb9-b38b9fe8238d-10a26edf > p')
    .should('have.text','The resale program reduced waste and opened up new revenue streams for brands due to which they acquire new customers and retain existing ones by offering them valuable reselling opportunities.')
  })

  it('should verify KUDO case studies', () => {
    cy.contains('KUDO’s Journey to Bridging Global Communications')
    .should('have.attr','href','/case-studies/kudo')
    .click()

    cy.title()
    .should("include","KUDO’s Journey to Bridging Global Communications")

    cy.get('.project-page-banner-description')
    .should('have.text','Translating the future of digital meetings where everyone speaks freely.')

    cy.get('.case-study-rich-text > h2 > strong')
    .should('have.text','Inside KUDO’s Futuristic Multilingual Platform')
    cy.get('.case-study-rich-text > :nth-child(2)')
    .should('have.text','KUDO provides an interpretation service that matches its clients with the perfect interpreters for meetings, webinars, and events on demand. It combines human and AI power into multilingual solutions that enable people to communicate effortlessly in any language, wherever they are.')
    cy.get('.case-study-rich-text > :nth-child(3)')
    .should('have.text','KUDO is sourced from a network of 12,000 vetted interpreters specializing in 200+ spoken and sign languages that match your subject matter expertise. It provides hourly pricing and an online payment system, allowing the purchase to be made in less than 3 minutes. The KUDO team helps host smooth multilingual meetings and events, from sound check to interpretation set-up. It also takes care of the details, so you can focus on connecting and collaborating with your global audience.')

    cy.get('.project-solutions-rich-text > h2 > strong')
    .should('have.text','Understanding the Challenges in Maintaining AI-powered Interpreter')
    cy.get('.project-solutions-rich-text > :nth-child(2)')
    .should('have.text','KUDO’s communication platform faced multifaceted challenges that impede seamless user experiences and efficient service delivery.')
    cy.get('.project-solutions-rich-text > :nth-child(3)')
    .should('have.text','The initial adoption of Elasticsearch yielded suboptimal results, as the dataset lacked the scale necessary to leverage its full capabilities, incurring unnecessary costs. Additionally, the integration of a third-party library, Zoom_rb ruby gem, presented limitations in handling error codes, negatively impacting user interactions and lacking support for interpretation during Zoom webinars. The reliance on live interpreters proved problematic due to occasional unavailability, requiring manual intervention. Furthermore, the integration of calendar systems posed difficulties with existing plugins, failing to meet the customization needs for interpreters’ schedules. Addressing these challenges was pivotal to enhancing the platform’s effectiveness and user satisfaction.')

    cy.get('.result-rich-text > h2 > strong')
    .should('have.text','How We Fulfilled Our Client’s Expectations?')
    cy.get('.result-rich-text > p')
    .should('have.text','Considering the challenges and limitations, we decided to implement our expertise that aligns with the KUDO platform’s stable and seamless working.')
    cy.get('ul > :nth-child(1)')
    .should('have.text','We transitioned to using raw SQL queries and database indexes within PostgreSQL to handle search functionality. Creating targeted indexes on relevant columns in PostgreSQL allowed for fast searches across our data without needing a dedicated search engine.')
    cy.get('ul > :nth-child(2)')
    .should('have.text','To improve the reliability and capabilities of Zoom integration, we decided to develop a custom wrapper. This in-house wrapper gave full control over error handling and detailed error messages. Also, it enabled the seamless interpretation support for webinars.')
    cy.get('ul > :nth-child(3)')
    .should('have.text','We also introduced AI interpretation into meetings and conducted extensive training in AI models to enable interpretation in over 20 languages.')
    cy.get('ul > :nth-child(4)')
    .should('have.text','Our development of a custom calendar tool allowed interpreters to easily indicate their availability by dragging their selection over multiple days. We used React’s drag-table-select to implement dragging functionality.')
    cy.get('ul > :nth-child(5)')
    .should('have.text','Furthermore, our custom calendar seamlessly integrates the display of different colors to correspond with the various availability statuses of interpreters, making it a tailor-made solution that precisely aligns with the platform’s needs.')

    cy.get('.heading-8')
    .should('have.text','Benefits that Paved The Way for Connections Beyond Borders')
    cy.contains('AI Interpretation')
    .should('have.text','AI Interpretation')
    cy.get('#w-node-f63917fc-0bab-68ec-ed14-5c4d83105098-10a26edf > p')
    .should('have.text','AI Interpretation revolutionized language barriers, offering a consistent and reliable solution. Users enjoy effortless communication as AI seamlessly facilitates interpretation, promoting inclusivity and expanding collaboration opportunities on the platform.')
    cy.contains('Multiple Languages')
    .should('have.text','Multiple Languages')
    cy.get('#w-node-b2706c5f-a224-fd15-7b6d-ba1158045284-10a26edf > p')
    .should('have.text','Support for multiple languages on the platform is a game-changer. Users experience a globalized communication environment, fostering diverse interactions and breaking down language barriers for a truly inclusive collaborative experience.')
    cy.contains('Smoother Experience')
    .should('have.text','Smoother Experience')
    // cy.get('#w-node-_6a23ea53-4b33-c074-a631-fffba163e780-10a26edf > p')
    // .should('have.text','The result was a smoother experience for users interacting with Zoom through our platform')
    cy.contains('Integrated Processes')
    .should('have.text','Integrated Processes')
    cy.get('#w-node-_94a3001f-91a9-a4f4-9fb9-b38b9fe8238d-10a26edf > p')
    .should('have.text','The processes are more simplified and well-integrated with interpreters and clients. Streamlined workflows and integrated features contribute to a seamless experience, empowering users with accessible and straightforward operations.')
  })

  it('should verify Intellirent’s case studies', () => {
    cy.contains('Intellirent’s Approach to Smarter Leasing')
    .should('have.attr','href','/case-studies/intellirent')
    .click()

    cy.title()
    .should("include","Intellirent’s Approach to Smarter Leasing")

    cy.get('.project-page-banner-description')
    .should('have.text','Facilitating the dynamic solution for property management with improved decision-making.')

    cy.get('.case-study-rich-text > h2 > strong')
    .should('have.text','Presenting Intellirent’s Innovative Story to Tenant Screening')
    cy.get('.case-study-rich-text > :nth-child(2)')
    .should('have.text','Intellirent as a latest online platform is designed to help property managers and landlords make smarter rental decisions by providing comprehensive and detailed tenant screening services, ensuring quality-oriented services.')
    cy.get('.case-study-rich-text > :nth-child(3)')
    .should('have.text','This product was introduced and developed to overcome the challenges of the traditional leasing process which is full of friction and delay. The most important factor is the right decision-making while finding potential renters, screening their capabilities, and comparing their applications to approving the most suitably qualified renters, thus simplifying the overall management.')

    cy.get('.project-solutions-rich-text > h2 > strong')
    .should('have.text','Understanding the Challenges of Maintaining Rental Information')
    cy.get('.project-solutions-rich-text > :nth-child(2)')
    .should('have.text','This case study was faced with major challenges that we helped overcome on the client’s side, delineated below:')
    cy.get('.project-solutions-rich-text > :nth-child(3)')
    .should('have.text','Previously, relying on the traditional leasing process, it was very tricky and critical for users to transfer data relevant to rental properties and maintain them for later use. Not only this, but high risks would have been faced and at some point, the users would have lost the data queries. Besides that, income verifications and other such crucial functions needed real-time authenticity and security of information, as the vital challenges faced by the client’s company.')

    cy.get('.result-rich-text > h2 > strong')
    .should('have.text','The Cutting-Edge Solutions Offered for Strategic Leasing')
    cy.get('.result-rich-text > p')
    .should('have.text','Contrary to the challenges faced by the client, our latest services provide an efficient solution to the client, hence resolving the problem:')
    cy.get('ul > :nth-child(1)')
    .should('have.text','We successfully optimized all the data queries and incorporated flexible ways to fetch the required data for this peculiar project.')
    cy.get('ul > :nth-child(2)')
    .should('have.text','Additionally, we changed the complete architecture so that desired data could be sent efficiently to another site or entity to automate the processes profoundly, with no chance of human error while implementing the automation.')
    cy.get('ul > :nth-child(3)')
    .should('have.text','Interestingly, we implemented Finicity API for real-time income verifications to facilitate and provide real-time data authenticity.')
    cy.get('ul > :nth-child(4)')
    .should('have.text','We also implemented other significant functions and feasibilities to facilitate this project’s success.')
    cy.get('ul > :nth-child(5)')
    .should('have.text','Moreover, We conducted detailed functional testing to avoid all types of execution errors.')

    cy.get('.heading-8')
    .should('have.text','Client-Centric Benefits that Empowered Rental Decision-Making')
    cy.contains('Improved Interface')
    .should('have.text','Improved Interface')
    cy.get('#w-node-f63917fc-0bab-68ec-ed14-5c4d83105098-10a26edf > p')
    .should('have.text','Once the system was revamped, the users got a better interface to witness well the easiest way to handle and maintain data that was previously lost.')
    cy.contains('Secure Transactions')
    .should('have.text','Secure Transactions')
    cy.get('#w-node-b2706c5f-a224-fd15-7b6d-ba1158045284-10a26edf > p')
    .should('have.text','The money transactions were handled well with a complete record of every instance, thus improving the level of security for each transaction.')
    cy.contains('Real-time Transformations')
    .should('have.text','Real-time Transformations')
    cy.get('#w-node-_6a23ea53-4b33-c074-a631-fffba163e780-10a26edf > p')
    .should('have.text','It reduced human efforts to only 2% and saved time while projecting real-time transformations, ensuring better efficiency.')
    cy.contains('Flexible System')
    .should('have.text','Flexible System')
    cy.get('#w-node-_94a3001f-91a9-a4f4-9fb9-b38b9fe8238d-10a26edf > p')
    .should('have.text','The accurate data was sent over different sites and verifications of various income values were made more flexible than ever')

  })
})